### ISSUE TITLE
Improve compatibility with Web Stories plugin

### ISSUE THREAD

**Issue by swissspidy** [Dan0sz/host-webfonts-locally#2]
I've just tested your plugin's compatibility with the [Web Stories WordPress plugin](https://wordpress.org/plugins/web-stories/) and it _almost_ works.

But because of the `is_amp()` check here, no conversion is made when visiting a story:

https://github.com/Dan0sz/host-webfonts-locally/blob/10cddc49f2f9d4cb7a19178ed8713e2710693861/includes/frontend/class-process.php#L355-L357

https://github.com/Dan0sz/host-webfonts-locally/blob/10cddc49f2f9d4cb7a19178ed8713e2710693861/includes/frontend/class-process.php#L415-L424

The Web Stories plugin also has an `is_amp_endpoint()` function, which is why the `is_amp()` method returns `true`.

But if I remove that check, it _just works_ and produces valid AMP just fine.

Could you perhaps shed some light on why this check was added (and essentially no-ops the functionality on AMP pages)?

The changelog says:

> Stylesheets on AMP pages would be rewritten to local stylesheets, while this is not supported by AMP.

But I don't see why that would not be supported.

**Comment by Dan0sz** [comment]
AMP only supports Google Fonts directly from the Google Fonts API. Adding the fonts as a local stylesheet would add to the total (limited) CSS quota allowed in AMP pages, which is usually used by themes to add their styles to an AMP page.

Besides, since the visitor is already on an AMP page (which is loaded from Google's servers) not loading the fonts from Google's servers would be inefficient.

the `is_amp_endpoint()` function was found in an AMP plugin (don't remember which one -- I think it was an older version of AMPforWP), so that's why it's there.

I'd have to research if this can safely be removed. I'll add it to my TODO.

**Comment by Dan0sz** [comment]
Nevermind, just found out Web Stories are basically AMP pages. It doesn't make sense to load local fonts on AMP pages as I explained above. So, I'm closing this.

**Comment by swissspidy** [comment]
That‘s a lot of misconceptions about AMP, as this would work perfectly fine, especially for stories. But alas.

Would you at least consider adding a filter so that other plugins could work around this behavior?

**Comment by Dan0sz** [comment]
I've looked it up again in the documentation, and it seems to agree with me: https://amp.dev/documentation/guides-and-tutorials/websites/develop/style_and_layout/custom_fonts

Then I found this ticket on Github, that says that the limit is raised to 75KB: https://github.com/ampproject/amphtml/issues/26466

Since AMP doesn't allow including external stylesheets, it'd have to be loaded inline. Some users have Google Fonts stylesheets of ~10KB. Adding that as an inline stylesheet will make them hit this limit quickly.

Regardless, when loading an AMP page, you're connecting to Google's servers (i.e. DNS) already, why would you want to waste another DNS lookup to connect to your own site/domain? It doesn't make sense, IMO.

If I'm missing something in my reasoning, please point it out to me.
